# Generated by Django 4.0.4 on 2022-05-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_people_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication_app.post')),
            ],
        ),
    ]
